apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-green
  labels:
    app: my-app
    color: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
      color: green
  template:
    metadata:
      labels:
        app: my-app
        color: green
    spec:
      containers:
      - name: my-app
        image: my-registry/my-app:v1  # Jenkins will overwrite this tag dynamically
        ports:
        - containerPort: 8080
